version: "3"
services:
  mongo:
    image: mongo:latest
   # command: --serviceExecutor adaptive
    ports: 
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    container_name: mongoPaint
    # restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
volumes:
  mongo-data:
    driver: local
