export {default as Sidebar} from './Sidebar'
export {default as Template} from './Template'
export {default as HomePage} from './Homepage'
export {default as SignUp} from './Signup'
export {default as Login} from './Login'
export {default as Admin} from './Admin'
export {default as PixelBoardCreate} from './FormCreatePB'
export {default as PixelBoard} from './PixelBoard'