name: "Paint Pixel React"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm config set legacy-peer-deps true
      - run: npm install
      - run: CI='' npm run build
