name: "Paint Pixel React"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm config set legacy-peer-deps true
      - run: npm install
      - run: CI='' npm run build
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.RSA_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/debian/paintpixel/html
            rm -rf *
            cd /home/debian/paintpixel/code
            git pull origin main
            npm run build
            cp -r /home/debian/paintpixel/code/build/* /home/debian/paintpixel/html
            sudo service nginx restart
